# Generated by Django 5.2.6 on 2025-09-22 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rag_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="source_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
